/**
 * Job lifecycle types.
 *
 * INTENT: Define the canonical job request, record, terminal result, and event shapes.
 * INPUT: None (pure type definitions)
 * OUTPUT: JobRequest, JobRecord, JobTerminalResult, JobStatus, JobEventType, JobEventPayload
 * SIDE EFFECT: None
 * FAILURE: N/A — compile-time only
 */

import type { AssetDescriptor } from "./assets.js";
import type { JobError } from "./errors.js";
import type { WorkflowSpec } from "./workflow.js";

/** Legal job lifecycle states. V1: no cancelled state. */
export type JobStatus = "created" | "running" | "completed" | "failed";

/** Lifecycle event types emitted by the engine. */
export type JobEventType =
  | "job:created"
  | "job:running"
  | "job:completed"
  | "job:failed";

/**
 * Host-submitted job request.
 *
 * Contains everything needed to begin execution: provider selection,
 * workflow reference, opaque input payload, and optional asset references.
 */
export interface JobRequest {
  /** Selected provider identifier. */
  readonly providerId: string;
  /** Workflow identifier for registry lookup, or inline workflow spec. */
  readonly workflowId?: string;
  readonly workflowSpec?: WorkflowSpec;
  /** Opaque input payload — provider owns interpretation. */
  readonly input: unknown;
  /** Optional asset references for the job. */
  readonly assets?: readonly AssetDescriptor[];
  /** Optional host-supplied metadata. */
  readonly metadata?: Record<string, unknown>;
}

/**
 * Terminal result envelope for completed jobs.
 *
 * Carries declared workflow output, output assets, and diagnostics.
 */
export interface JobTerminalResult {
  /** Declared workflow output payload. */
  readonly output: unknown;
  /** Output asset descriptors produced by the workflow. */
  readonly assets: readonly AssetDescriptor[];
  /** Execution diagnostics (step timings, cleanup outcomes, etc.). */
  readonly diagnostics?: Record<string, unknown>;
}

/**
 * Engine-owned job record — canonical current snapshot for each job.
 *
 * Hosts read this for authoritative status. Events are transient notifications;
 * the store is the source of truth.
 */
export interface JobRecord {
  /** Unique job identifier generated by the engine. */
  readonly jobId: string;
  /** Current lifecycle state. */
  readonly status: JobStatus;
  /** Snapshot of the original request. */
  readonly request: JobRequest;
  /** Active step identifier (null when not running). */
  readonly activeStepId: string | null;
  /** Monotonic event sequence counter. */
  readonly eventSequence: number;
  /** Creation timestamp (ISO 8601). */
  readonly createdAt: string;
  /** Last update timestamp (ISO 8601). */
  readonly updatedAt: string;
  /** Terminal result (set when status === "completed"). */
  readonly result: JobTerminalResult | null;
  /** Terminal error (set when status === "failed"). */
  readonly error: JobError | null;
}

/**
 * Lifecycle event payload emitted by the engine.
 *
 * Hosts subscribe to these for reactive updates. The store remains
 * the authoritative current snapshot — events are transient.
 */
export interface JobEventPayload {
  /** Job identifier. */
  readonly jobId: string;
  /** Lifecycle state at time of emission. */
  readonly status: JobStatus;
  /** Event timestamp (ISO 8601). */
  readonly timestamp: string;
  /** Monotonic sequence number for ordering. */
  readonly sequence: number;
  /** Active step identifier when available. */
  readonly activeStepId: string | null;
  /** Compact job-envelope summary for host consumption. */
  readonly summary: {
    readonly providerId: string;
    readonly workflowId: string | null;
  };
  /** Optional diagnostics or evidence trace data. */
  readonly diagnostics?: Record<string, unknown>;
}
